defaults: &defaults
  evernote:
     access_token:
     consumer_key:
     consumer_secret:
     sandbox: true

     shared_notebooks:
       - comment:
         share_key:

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
